### ISSUE TITLE
Add all options for roku-deploy

### ISSUE THREAD

**Issue by jonnyijapan** [rokucommunity/vscode-brightscript-language#193]
It would be nice to be able to use all of the roku-deploy options (in rokudeploy.json normally if using roku-deploy only) directly from launch.json.

**Comment by TwitchBronBron** [comment]
The launch.json is specifically used for launching debug sessions, so not all of the roku-deploy options make sense to be added to `launch.json` (like `signingPassword` for example, which is used to create Roku store-publishable packages). If you intend to create a Roku store-publishable package, you should use `roku-deploy` directly to create the package and specify the options you want. 

I can definitely get on board with adding `incrementBuildNumber` to the `launch.json` options though, because I can see that being useful. Is there any other options other than `incrementBuildNumber` that you would like to see added that relate to debugging in the extension?

**Comment by TwitchBronBron** [comment]
@jonnyijapan can you specify which roku-deploy options are missing that you would like to have added to the launch.json configuration?

**Comment by TwitchBronBron** [comment]
Closing due to lack of response from question author.
