### ISSUE TITLE
Support sourcemaps

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/vscode-brightscript-language#202]
The debugger should support sourcemaps. This would allow any number of preprocessors to gain full debug support in the IDE

**Comment by TwitchBronBron** [comment]
@georgejecook, I have started working on this

**Comment by chrisdp** [comment]
Woot, I am very excited for this! 

One thing to do early is keep component libraries in mind and how they may appear to have file conflicts but because they are compiled in there own sandbox they are not actually conflicting. 

I would be happy to experiment on alphas of this work with potential maps created form a project I am working on so we can find support issues as soon into this as possible.

**Comment by TwitchBronBron** [comment]
The first thing I am doing is implementing the maps within the breakpoint-insertion code. So, technically every project will be using sourcemaps soon. :D I figured that's a good way to validate it right out the gate. Every file with a breakpoint will get rewritten using the source-map library. Then we will read those maps to translate the line numbers back to the source (instead of our kludgy line-offset arrays that we have now)

**Comment by TwitchBronBron** [comment]
And yes, I will definitely keep component libraries in mind. They will be first-class citizens in this endeavor, as I don't want to break them.

**Comment by TwitchBronBron** [comment]
Just an update, I have a working version of the extension with sourcemap support. Still have a few bugs to track down, but its mostly ready. I'll be testing and validating in the next week or two, but this is very close.
