### ISSUE TITLE
Ctrl-click navigation should not suggest files in out folder

### ISSUE THREAD

**Issue by sschaub** [rokucommunity/vscode-brightscript-language#267]
When using ctrl-click to navigate in .brs files - sometimes vscode shows two possibilities, one of which is in the out/.roku-deploy-staging folder. If I inadvertently click that one and edit, I lose the edit when I redeploy. 

I recommend excluding the out folder from the ctrl-click navigation search.

**Comment by sschaub** [comment]
The out folder can be excluded by including in .vscode/settings.json:

    {
      "files.exclude": {
        "out": true,
        "search.exclude": {
            "files.watcherExclude": {
                "out": true
            }
        }
      }
    }

**Comment by TwitchBronBron** [comment]
I believe this only happens when running with the language server disabled, which falls back to the more primitive "scan every file in the workspace" mode. #391 fixes this issue by excluding the entire `${workspaceFolder}/out` folder when in that mode. 

There's nothing that can be done about when in language server mode, because the user specifically maintains the entire list of files in the files array, so if they don't want to see those files, just exclude them from the files array.
