### ISSUE TITLE
ComponentLibrary this file

### ISSUE THREAD

**Issue by xoceunder** [rokucommunity/vscode-brightscript-language#293]
I have a problem that I am using ComponentLibrary to be able to load templates but under a zip but the zip is as encrypted
@AlejandroJL

**Comment by chrisdp** [comment]
@xoceunder can you give some more details as to what issue(s) you are seeing? 

For example: is the Component Library failing to load, are you trying to debug the Component Library itself, etc.

**Comment by xoceunder** [comment]
Here is the application that I am managing to clone to be able to make different changes 
https://github.com/xoceunder/IPTVSmartersProRoku

@chrisdp

**Comment by chrisdp** [comment]
Hey @xoceunder, after looking at the repo it looks like you your project is loading a remote component library. The extension only support working on component libraries in which you have access to the source code for.

**Comment by xoceunder** [comment]
is there any way to get the code 
@chrisdp

**Comment by chrisdp** [comment]
The extension does not have support for extracting code from a component library. 

The current support is limited to packaging your source code into a zip and staticky hosting the files on your local computer so that you can load the code in your Roku channel for development. 

If you need access to the source code to make modifications you will need to reach out to the code owners of the library you are loading into your channel.

**Comment by TwitchBronBron** [comment]
We don't have any current plans of supporting debugging component libraries for which you don't have the source code, and especially not encrypted component libraries.
