### ISSUE TITLE
launch.json is sourced before being saved

### ISSUE THREAD

**Issue by DusanLesan** [rokucommunity/vscode-brightscript-language#320]
I have a habit to hardcode the host value in launch.json file. Also I am usually relaying on autosave on run. Because of this, I am encountering a small issue when running the debugger. 
For example, if I have hardcoded host IP to be 1.1.1.1 and want to switch to other device, I would go to launch.json and change the IP to match second device. Without saving the file I would run the debugger expecting changes to be applied during the current run. That is not the case and debugger is trying to connect to previous device used. If I remember to save, everything is Ok

![image](https://user-images.githubusercontent.com/20520590/127778199-702dd5b6-c5d8-41d2-88b7-479859e50b14.png)

**Comment by chrisdp** [comment]
In your example you're saying this happens when you modify the launch.json and do not save it and rely on the auto save for that file as well as your workspace files?

If so there isn't much we can do to address that as the contents on the launch configuration is supplied by vs code it self. Our extension is provided a launch configuration by VS Code when you run we don't look it up. 

That being said you may be able to work around this by using an env file and putting your host ip in there. That we do read our selfs.

**Comment by DusanLesan** [comment]
@chrisdp Thank you for the response. That is right, issue is with me not saving on my own. I was hoping that we can modify the extension to have it save all before continuing with anything else. You can close the issue if nothing can be done on extension side

**Comment by chrisdp** [comment]
Yea, the save on run is a VS Code level setting so there isn't anything we can do.

Thanks for filing the issue! Please open any other problems or improvements you think we can make!
