### ISSUE TITLE
Feature request: add ability to rekey/sign apps

### ISSUE THREAD

**Issue by kbunch** [rokucommunity/vscode-brightscript-language#61]

**Comment by kbunch** [comment]
I need to learn more about the options in VS code, but my initial thought is that it would be another entry in the launch.json config. You could have one for testing/debugging, one for creating prod (not testing). If that can be done in the current context, that would be awesome. If it has to be done with a different command, that would be fine too. The main point would be using the same types of configurations that we use for testing that we do with automating the prod builds.

**Comment by TwitchBronBron** [comment]
@kbunch this feature was added to roku-deply. See its [options list ](https://github.com/TwitchBronBron/roku-deploy#options) for information. 

@triwav are you using the rekey functionality from within the extension at all?

**Comment by triwav** [comment]
@TwitchBronBron I use the roku-deploy npm module to use it. It could definitely be added to the extension but I have no plans to add that any time soon since we already run our script from the command line anyways.

**Comment by kbunch** [comment]
@TwitchBronBron  @triwav It would be nice to add this to the extension as well just as an option for users. The use case would be to have 2 different setups in your config one for staging and one for prod. The one for prod would rekey the machine, repackage it, and pull the pkg locally.

**Comment by triwav** [comment]
Sure understand the convenience but it's a good amount of work. If you want to do it in Vscode you could write a script to use roku-deploy to do it. Only around 10 lines of code.

**Comment by chrisdp** [comment]
To add to this, I definitely agree that this should be in the ext in my opinion but at the same time I also think this would be a lower priority item. 

The most flexible option is for users to ether leverage pre-launch tasks or create there own tasks using node that leverage roku-deploy. Since most people do a lot more then just create a PKG file, a lot of users will want tagging and committing. Possibly even automatic ticket creation in their ticket systems. To add this with enough support for most people would require a lot of work.

**Comment by kbunch** [comment]
@triwav @chrisdp @TwitchBronBron 
To be clear, what @chrisdp is suggesting is an advanced user and they'd probably be using roku-deploy directly with an automated process. I'm breaking users into 2 different sets advanced and junior. A junior potentially working alone with no automated processes would probably just want the ability to create a packaged/signed build directly from the IDE. They wouldn't care about hooks to the repo, etc. So in essence you are just building it for the most basic use case.

**Comment by chrisdp** [comment]
Just going thought the open issues and saw this. @kbunch @triwav @TwitchBronBron what about adding a command to the extension that then asks from what launch config would you like to build the package from?

**Comment by chrisdp** [comment]
This issue hasn't been completely resolved. That being said we add some commands used in this process such as gen key and such. Something we still need to revisit. We have been talking about some sort of set up wizard. If that becomes a reality it might be possible to support this at that point since we would know a lot more about the project set up.

**Comment by chrisdp** [comment]
@TwitchBronBron I think this issue can now be consider resolved as of #431 ?

**Comment by TwitchBronBron** [comment]
Agreed. Closing. :)
